###
POST http://localhost:8080/api/currency
Authorization: Basic moderator moderator
Content-Type: application/json

{
  "name": "USD",
  "active": true
}

###
GET http://localhost:8080/api/currency
Authorization: Basic moderator moderator

###
DELETE http://localhost:8080/api/currency/1
Authorization: Basic moderator moderator