###
POST http://localhost:8080/api/measurement
Authorization: Basic moderator moderator
Content-Type: application/json

{
  "name": "Kilogram",
  "active": true
}

###
GET http://localhost:8080/api/measurement
Authorization: Basic moderator moderator

###
DELETE http://localhost:8080/api/measurement/1
Authorization: Basic admin admin