spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  data:
    rest:
      base-path: api
  servlet:
    multipart:
      enabled: true
      max-file-size: 25MB
      max-request-size: 25MB
attachment:
  download:
    url: api/attachment/download